---
# Install nginx

- name: Install nginx
  apt: name=nginx state=present

- name: Remove the default nginx site configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add the todo nginx configuration
  template: src=todo.j2 dest=/etc/nginx/sites-enabled/todo
  notify: restart nginx