---
# Install PHP-FPM

- name: Install python-software-properties
  apt: name=python-software-properties state=present

- name: Add apt repository ppa:ondrej/php
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install PHP 7.2
  apt:
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - php7.2
    - php7.2-cli
    - php7.2-curl
    - php7.2-dom
    - php7.2-fpm
    - php7.2-gd
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-sqlite3
    - zip
    - unzip

- name: Configure PHP-FPM
  template: src=symfony.ini.j2 dest=/etc/php/7.2/fpm/conf.d/symfony.ini
  notify: restart php7.2-fpm

- name: Configure PHP-FPM pool
  template: src=symfony.pool.conf.j2 dest=/etc/php/7.2/fpm/pool.d/symfony.pool.conf
  notify: restart php7.2-fpm
