---
# Installs the MySQL client

- name: Install the MySQL client
  apt: name=mysql-client state=present

- name: Install MySQL
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  become: yes
  with_items:
    - python-mysqldb
    - mysql-server

- name: Start the MySQL service
  become: yes
  service: 
    name: mysql 
    state: started
    enabled: true

- name: update mysql root password for all root accounts
  become: yes
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 